version: "2"

services:
  nginx:
    image: pixelfordinner/nginx
    container_name: pixelcloud-nginx_proxy-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./volumes/conf.d:/etc/nginx/conf.d:ro"
      - "./volumes/vhost.d:/etc/nginx/vhost.d:ro"
      - "./volumes/certs:/etc/nginx/certs:ro"
      - "./volumes/html:/usr/share/nginx/html:rw"
      - "./volumes/logs:/var/log/nginx"
  docker-gen:
    image: jwilder/docker-gen:0.7.3
    container_name: pixelcloud-nginx_proxy-docker_gen
    restart: always
    depends_on:
      - nginx
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./templates:/etc/docker-gen/templates:ro"
      - "./volumes/conf.d:/etc/nginx/conf.d:rw"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup pixelcloud-nginx_proxy-nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  lets-encrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.6
    container_name: pixelcloud-nginx_proxy-lets_encrypt
    restart: always
    depends_on:
      - nginx
      - docker-gen
    volumes_from:
      - nginx
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./volumes/vhost.d:/etc/nginx/vhost.d:rw"
      - "./volumes/certs:/etc/nginx/certs:rw"
      - "./volumes/html:/usr/share/nginx/html:rw"
    environment:
      - "NGINX_DOCKER_GEN_CONTAINER=pixelcloud-nginx_proxy-docker_gen"
     # - "ACME_CA_URI=https://acme-staging.api.letsencrypt.org/directory"
     # - "DEBUG=true"

networks:
  proxy-tier:
    external:
      name: "nginx-proxy-public"
